[package]
name = "qt-experiments"
version = "0.1.0"
authors = ["leo60228 <leo@60228.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qmetaobject = "0.1.4"
cstr = "0.2.5"
derivative = "2.1.1"
